server:
  port: 83

spring:
  application:
    name: cloud-order-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  nacos-user-service: http://nacos-pay-service

