server:
  port: 8002

spring:
  application:
    name: cloud-pay-service
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springcloud?serverTimezong=UTC
      username: root
      password: 123456

mybatis:
  type-aliases-package: com.sc.bean
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    #表示是否将自己注入EurekaServer，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须使用true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: pay8002
    #访问路径可以显示ip地址
    prefer-ip-address: true