server:
  port: 84

spring:
  application:
    name: cloud-order-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
service-url:
  nacos-user-service: http://nacos-pay-service
#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
